import type { NextPage } from 'next'
import Head from 'next/head'
import TableGrid from '../components/table-grid/table-grid'
import CATS from '../page-components/index/data'
import columns from '../page-components/index/columns'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Table grid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1>Editable Table</h1>
      </header>
      <main className={styles.main}>
        <div className={styles.tableContain}>
          <TableGrid tableData={CATS} tableColumns={columns} />
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Navigate cells with arrow keys. Enter or click to edit.
        </a>
      </footer>
    </div>
  )
}

export default Home
